# -----------------------
# clean, slice, toggle2, slice2, cook
# -----------------------

train:

  - name: "0.pickup"
    task_kinds: pickup
    num_dists: 0

  - name: "1.place"
    task_kinds: place
    num_dists: 0

  - name: "2.slice"
    task_kinds: slice
    num_dists: 0

  - name: "3.pickup_sliced"
    task_kinds: pickup_sliced
    num_dists: 0

  - name: "4.place_sliced"
    task_kinds: place_sliced
    num_dists: 0
