train:

  - name: pickup
    task_kinds: pickup
    num_dists: 0

  - name: clean
    task_kinds: clean
    num_dists: 0

  - name: slice
    task_kinds: slice
    num_dists: 0

  - name: chill
    task_kinds: chill
    num_dists: 0

  - name: pickup_cleaned
    task_kinds: pickup_cleaned
    num_dists: 0

  - name: pickup_sliced
    task_kinds: pickup_sliced
    num_dists: 0

  - name: pickup_chilled
    task_kinds: pickup_chilled
    num_dists: 0

  - name: pickup_dists2
    task_kinds: pickup
    num_dists: 2

  - name: clean_dists2
    task_kinds: clean
    num_dists: 2

  - name: slice_dists2
    task_kinds: slice
    num_dists: 2

  - name: chill_dists2
    task_kinds: chill
    num_dists: 2

  - name: pickup_cleaned_dists2
    task_kinds: pickup_cleaned
    num_dists: 2

  - name: pickup_sliced_dists2
    task_kinds: pickup_sliced
    num_dists: 2

  - name: pickup_chilled_dists2
    task_kinds: pickup_chilled
    num_dists: 2

test:

  - name: train_pickup_cleaned
    task_kinds: pickup_cleaned
    room_size: 8
    num_dists: 5

  - name: train_pickup_sliced
    task_kinds: pickup_sliced
    room_size: 8
    num_dists: 5

  - name: train_pickup_chilled
    task_kinds: pickup_chilled
    room_size: 8
    num_dists: 5
