train:

  - name: "0.pickup"
    task_kinds: pickup
    num_dists: 0

  - name: "0.toggle"
    task_kinds: toggle
    num_dists: 0

  - name: "1.pickup_dists"
    task_kinds: pickup
    num_dists: 2

  - name: "1.toggle_dists"
    task_kinds: toggle
    num_dists: 2

test:

  - name: "0.toggle2" # length 2
    task_kinds: toggle2
    use_subtasks: True
    num_dists: 0


  - name: "0.toggle3" # length 2
    task_kinds: toggle3
    use_subtasks: True
    num_dists: 0


  - name: "0.toggle_and_pickup" # length 3
    task_kinds: toggle_and_pickup
    use_subtasks: True
    num_dists: 0

  - name: "1.toggle_and_pickup_dists" # length 3
    task_kinds: toggle_and_pickup
    use_subtasks: True
    num_dists: 2
