train:

  # -----------------------
  # clean
  # -----------------------
  - name: pickup
    task_kinds: pickup
    num_dists: 0

  - name: toggle
    task_kinds: toggle
    num_dists: 0

  - name: clean
    task_kinds: clean
    num_dists: 0

  - name: pickup_cleaned
    task_kinds: pickup_cleaned
    num_dists: 0

  # -----------------------
  # slice
  # -----------------------
  - name: slice
    task_kinds: slice
    num_dists: 0

  - name: pickup_sliced
    task_kinds: pickup_sliced
    num_dists: 0

  # -----------------------
  # 2 objects
  # -----------------------
  - name: toggle2
    task_kinds: toggle2
    num_dists: 0

  - name: slice2
    task_kinds: slice2
    num_dists: 0

  # -----------------------
  # cook
  # -----------------------
  - name: cook
    task_kinds: cook
    taskarg_options:
      y: [pot]
    num_dists: 0


test:

  - name: toggle_and_slice # length 3
    task_kinds: toggle_and_slice
    num_dists: 0

  - name: clean_and_toggle # length 4
    task_kinds: clean_and_toggle
    num_dists: 0

  - name: clean_and_slice # length 5
    task_kinds: clean_and_slice
    num_dists: 0

  - name: clean_and_slice_and_toggle # length 6
    task_kinds: clean_and_slice_and_toggle
    num_dists: 0


task_reps:

  toggle: turnon x
  clean: clean x
  slice: slice x
  cook: cook x
